import { useMigrations } from 'drizzle-orm/expo-sqlite/migrator';
import { db } from './index';
// @ts-ignore - The migrations module is generated by drizzle-kit
import migrations from '../../../../drizzle/migrations';

export function useDbMigrations() {
  const { success, error } = useMigrations(db, migrations);
  return { success, error };
}
